name: Execute Render Secret Script

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every hour (adjust this to your schedule)
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Render Secret Script
        env:
          RENDER_SECRET_KEY: ${{ secrets.RENDER_API_KEY }} # Add Render API key as a GitHub secret
        run: |
          # Fetch the Render secret file using Render API
          curl -X GET \
            -H "Authorization: Bearer $RENDER_SECRET_KEY" \
            https://api.render.com/v1/services/srv-coujuja1hbls73886560/environment \
            | jq -r '.[] | select(.key=="schedule_script.js") | .value' > scheduled_script.js

      - name: Execute Script
        run: |
          node scheduled_script.js
